[package]
name = "kakoi_lib"
version = "0.1.0"
authors = ["Michael MacLeod <michaelmmacleod@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

float-cmp = "0.8.0"
svg = "0.9.0"
