[package]
name = "kakoi"
version = "0.1.0"
authors = ["Michael MacLeod <michaelmmacleod@gmail.com>"]
edition = "2018"

[[bin]]
name = "main"
doc = false

[dependencies]

float-cmp = "0.8.0"
svg = "0.9.0"
petgraph = "0.5.1"
bitvec = "0.21.0"